// #pragma link C++ class L0FileReader+;
// #pragma link C++ class Input+;
#pragma link C++ class EventGenerator+;
// #pragma link C++ class AraSimFileReader+;
#pragma link C++ class FileReader+;
#pragma link C++ class SimFileReader+;
#pragma link C++ class TreeWriter+;
#pragma link C++ class EventData+;
#pragma link C++ class SimData+;
// #pragma link C++ class Output+;
// #pragma link C++ class Parser+;
// #pragma link C++ class Configuration+;
// #pragma link C++ class ConfigVertex+;
// #pragma link C++ class std::vector<ConfigVertex>+;
#pragma link C++ class Headers+;
#pragma link C++ class Hks+;
#pragma link C++ class Triggers+;
#pragma link C++ class Times+;
#pragma link C++ class Waveforms+;
#pragma link C++ class TimeStamp+;
#pragma link C++ class RunHeader+;
#pragma link C++ class L2Data+;
