# SOURCES += Input.cc 
SOURCES += EventGenerator.cc 
# SOURCES += L0FileReader.cc 
# SOURCES += AraSimFileReader.cc
SOURCES += FileReader.cc
SOURCES += SimFileReader.cc
SOURCES += EventData.cc
SOURCES += SimData.cc
SOURCES += TreeWriter.cc
# SOURCES += Output.cc
# SOURCES += Parser.cc
# SOURCES += Configuration.cc ConfigVertex.cc
SOURCES +=L2Data.cc