// #include "Tools.h"
// #include "Constants.h"
// #include "Vector.h"
// #include "Position.h"
// #include "EarthModel.h"
#include "IceModel.h"
// #include "Efficiencies.h"
#include "Spectra.h"
#include "Event.h"
// #include "Trigger.h"
#include "Detector.h"
#include "Settings.h"
// #include "signal.hh"
// #include "counting.hh"
// #include "Primaries.h"
#include "Report.h"
//#include "eventSimDict.h"

// #include "Ray.h"
// #include "RaySolver.h"
// class EarthModel; //class

#include "UsefulAraStationEvent.h"
#include "UsefulIcrrStationEvent.h"
#include "araIcrrStructures.h"
